//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgiliFood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_pedido
    {
        public int id_pedido { get; set; }
        public int id_funcionario { get; set; }
        public int id_fornecedor { get; set; }
        public int id_produto { get; set; }
        public int quantidade_produto { get; set; }
        public System.DateTime date_pedido { get; set; }
    
        public virtual tb_fornecedor tb_fornecedor { get; set; }
        public virtual tb_funcionario tb_funcionario { get; set; }
        public virtual tb_produtos tb_produtos { get; set; }
    }
}
