//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgiliFood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_produtos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_produtos()
        {
            this.tb_pedido = new HashSet<tb_pedido>();
        }
    
        public int id_produto { get; set; }
        public string nome_produto { get; set; }
        public int id_fornecedor { get; set; }
        public bool status_produtos { get; set; }
    
        public virtual tb_fornecedor tb_fornecedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_pedido> tb_pedido { get; set; }
    }
}
